name: "Mi primer workflow"

on:
  workflow_dispatch:
  
  push:
    branches: 
    - main
    - feature/*

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          version: 18
        
      - name: Install & Build
        run: | 
          npm ci --silent
          npm run build
        working-directory: .
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            src/*.js
            !node_modules
  
